import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np
import trimesh

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))
sys.path.insert(0, str(project_root / "third_party" / "utils_simba"))

from utils_simba.logger import get_logger
from utils_simba.rerun import load_mesh_as_trimesh

logger = get_logger(__name__)


def _get_aligned_axis(mesh, frame_idx=None):
    """Return which axis (0=X, 1=Y, 2=Z) the mesh is aligned to.

    The principal eigenvector (largest eigenvalue from PCA) gives the direction
    of greatest vertex spread. The aligned axis is the component with the
    largest absolute value in that eigenvector.
    """
    verts = np.array(mesh.vertices)
    cov = np.cov(verts, rowvar=False)
    eigenvalues, eigenvectors = np.linalg.eigh(cov)
    # Principal axis = eigenvector with largest eigenvalue (last column from eigh)
    principal = eigenvectors[:, -1]
    abs_principal = np.abs(principal)
    aligned = int(np.argmax(abs_principal))
    axis_names = ["X", "Y", "Z"]
    fid = f"Frame {frame_idx:04d}" if frame_idx is not None else ""
    logger.debug(f"  {fid}: abs principal = {abs_principal} -> aligned={axis_names[aligned]}")
    return aligned


def main(args):
    sam3d_dir = Path(f"{args.dataset_dir}/{args.scene_name}/SAM3D")

    # Load frame list after 2D filter generated by pipeline_sam3d_filter_2D.py
    frame_list_file = sam3d_dir / "frame_list_after_depth_filtered.txt"
    with open(frame_list_file, "r") as f:
        frame_indices = [int(line.strip()) for line in f if line.strip()]
    logger.info(f"Loaded {len(frame_indices)} frames from {frame_list_file}")

    # For each frame, get the aligned axis, then filter by majority axis
    axis_names = ["X", "Y", "Z"]
    frame_axes = {}  # frame_idx -> aligned axis (0=X, 1=Y, 2=Z)
    for frame_idx in list(frame_indices):
        fid = f"{frame_idx:04d}"
        frame_dir = sam3d_dir / fid
        mesh = load_mesh_as_trimesh(frame_dir)
        if mesh is None:
            logger.warning(f"  Frame {fid}: no mesh found, keeping frame")
            continue
        frame_axes[frame_idx] = _get_aligned_axis(mesh, frame_idx)

    # Determine the dominant aligned axis (majority vote)
    if frame_axes:
        axis_counts = np.bincount(list(frame_axes.values()), minlength=3)
        dominant_axis = int(np.argmax(axis_counts))
        logger.info(f"Axis counts: X={axis_counts[0]}, Y={axis_counts[1]}, Z={axis_counts[2]} -> dominant={axis_names[dominant_axis]}")

        # Filter frames not aligned with the dominant axis
        filtered_out = []
        for frame_idx, axis in frame_axes.items():
            if axis != dominant_axis:
                logger.info(f"  Frame {frame_idx:04d}: aligned={axis_names[axis]}, expected={axis_names[dominant_axis]}, filtering out")
                filtered_out.append(frame_idx)
                frame_indices.remove(frame_idx)
        if filtered_out:
            logger.info(f"Filtered {len(filtered_out)} frames with non-{axis_names[dominant_axis]}-aligned meshes: {filtered_out}")

    # For each frame, load camera intrinsic and poses from camera.json
    # generated by ho3d_obj_SAM3D_gen in run_wonder_hoi.py
    distances = {}
    projected_points = {}

    for frame_idx in frame_indices:
        fid = f"{frame_idx:04d}"
        camera_json = sam3d_dir / fid / "camera.json"
        if not camera_json.exists():
            logger.warning(f"  Frame {fid}: camera.json not found, skipping")
            continue

        with open(camera_json, "r") as f:
            camera = json.load(f)

        K = np.array(camera["K"], dtype=np.float64)       # (3, 3)
        o2c = np.array(camera["blw2cvc"], dtype=np.float64)  # (4, 4)

        # Project the origin (0, 0, 0) into the image plane
        origin_world = np.array([0.0, 0.0, 0.0, 1.0])
        origin_cam = o2c @ origin_world  # (4,)
        origin_cam_3d = origin_cam[:3]

        # Skip if behind camera
        if origin_cam_3d[2] <= 0:
            logger.warning(f"  Frame {fid}: origin behind camera, skipping")
            continue

        # Project to 2D: p = K @ [x, y, z]^T, then normalize
        p_2d = K @ origin_cam_3d
        u = p_2d[0] / p_2d[2]
        v = p_2d[1] / p_2d[2]

        # Optical center from intrinsics
        cx = K[0, 2]
        cy = K[1, 2]

        # Calculate the distance between the projected point and the optical center
        dist = np.sqrt((u - cx) ** 2 + (v - cy) ** 2)

        distances[frame_idx] = dist
        projected_points[frame_idx] = (u, v)
        logger.debug(f"  Frame {fid}: projected=({u:.1f}, {v:.1f}), optical_center=({cx:.1f}, {cy:.1f}), dist={dist:.1f}")

    # Save projected points and distances for debug
    debug_path = sam3d_dir / "frame_list_3d_filter_debug.txt"
    with open(debug_path, "w") as f:
        f.write("frame_idx\tproj_u\tproj_v\tdistance\n")
        for idx in sorted(distances, key=lambda i: distances[i]):
            u, v = projected_points[idx]
            f.write(f"{idx:04d}\t{u:.1f}\t{v:.1f}\t{distances[idx]:.1f}\n")
    logger.info(f"Saved debug info to {debug_path}")

    # Sort by distance (ascending — closer to optical center is better) and select top max_frame
    sorted_by_dist = sorted(distances, key=lambda i: distances[i])
    selected = sorted_by_dist[:args.max_frame]

    out_path = sam3d_dir / "frame_list_after_3d_filtered.txt"
    with open(out_path, "w") as f:
        for idx in selected:
            f.write(f"{idx}\n")
    logger.info(f"Saved 3D-filtered frame list ({len(selected)} frames) to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Filter frames by optical center for SAM3D")
    parser.add_argument("--dataset_dir", type=str, required=True)
    parser.add_argument("--scene_name", type=str, required=True)
    parser.add_argument("--max_frame", type=int, default=20, help="Max frames to keep after 3D filtering")

    args = parser.parse_args()
    main(args)
