import argparse
from pathlib import Path

import numpy as np

from robust_hoi_pipeline.pipeline_joint_opt_utils import (
    prepare_joint_opt_inputs,
    register_remaining_frames,
    load_image_info,
)
from robust_hoi_pipeline.neus_integration import _find_latest_checkpoint


def main(args):
    data_dir = Path(args.data_dir)
    out_dir = Path(args.output_dir)
    cond_idx = args.cond_index

    SAM3D_dir = data_dir / "SAM3D_aligned_post_process"
    data_preprocess_dir = out_dir / "pipeline_preprocess"
    tracks_dir = out_dir / "pipeline_corres"

    (
        frame_indices,
        preprocessed_data,
        tracks,
        vis_scores,
        tracks_mask,
        cond_cam_to_obj,
        cond_local_idx,
    ) = prepare_joint_opt_inputs(
        data_preprocess_dir=data_preprocess_dir,
        tracks_dir=tracks_dir,
        sam3d_dir=SAM3D_dir,
        cond_idx=cond_idx,
    )

    sam3d_root_dir = SAM3D_dir / f"{cond_idx:04d}"

    # Load image_info generated by pipeline_joint_opt_reg_first_frame.py
    joint_opt_dir = out_dir / "pipeline_joint_opt"
    image_info = load_image_info(joint_opt_dir, cond_idx)

    # Load NeuS checkpoint generated by pipeline_joint_opt_reg_first_frame.py
    neus_ckpt = _find_latest_checkpoint(joint_opt_dir)
    if neus_ckpt is not None:
        print(f"Loaded NeuS checkpoint: {neus_ckpt}")
    else:
        print("Warning: No NeuS checkpoint found, NeuS resume will be skipped")

    neus_total_steps = 20000

    # Register remaining frames with incremental NeuS
    register_remaining_frames(
        image_info, preprocessed_data, out_dir, cond_idx,
        neus_ckpt=neus_ckpt, neus_total_steps=neus_total_steps,
        sam3d_root_dir=sam3d_root_dir,
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Joint optimization pipeline - register remaining frames")
    parser.add_argument("--data_dir", type=str, required=True,
                        help="Input data directory (e.g., HO3D_v3/train/SM2)")
    parser.add_argument("--output_dir", type=str, required=True,
                        help="Output directory for results")
    parser.add_argument("--cond_index", type=int, default=0,
                        help="Condition frame index (keyframe with known SAM3D pose)")

    args = parser.parse_args()
    main(args)
