import argparse
import json
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))
sys.path.insert(0, str(project_root / "third_party" / "utils_simba"))

from utils_simba.logger import get_logger

logger = get_logger(__name__)


def main(args):
    scene_dir = Path(args.scene_dir)


    # Load frame_list_after_align_filter.txt generated by pipeline_sam3d_align_filter
    filtered_path = scene_dir / "SAM3D_align_filter" / "frame_list_align_filter.txt"
    if not filtered_path.exists():
        logger.error(f"{filtered_path} not found.")
        return
    with open(filtered_path, "r") as f:
        filtered_ids = [line.strip() for line in f if line.strip()]

    # Pick the first filtered frame as the best id (zero-padded to 4 digits)
    best_id = f"{int(filtered_ids[0]):04d}"


    logger.info(f"Best id: {best_id}")

    # Save best id
    out_path = scene_dir / "SAM3D_align_filter" / "best_id.txt"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(best_id)
    logger.info(f"Saved best id to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Find best frame id from filtered frames by score")
    parser.add_argument("--scene_dir", type=str, required=True,
                        help="Scene directory containing SAM3D_aligned_fp/")
    args = parser.parse_args()
    main(args)
