import argparse
import os
import pickle
import sys
from pathlib import Path

import cv2
import numpy as np

project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))
sys.path.insert(0, str(project_root / "../" / "third_party" / "utils_simba"))

from utils_simba.depth import depth2xyzmap, get_depth


def _load_intrinsics(meta_path: str) -> np.ndarray:
    """Load camera intrinsics from meta pickle file."""
    with open(meta_path, "rb") as f:
        meta = pickle.load(f)
    return np.array(meta["intrinsics"], dtype=np.float32)


def _geometry_quality(depth: np.ndarray, K: np.ndarray, mask: np.ndarray) -> float:
    """Compute geometry quality via SVD of masked object point cloud.

    Returns the ratio of the smallest to largest singular value (0–1).
    A value close to 1 means the points are well-spread in 3D (good geometry);
    a value close to 0 means degenerate/planar/sparse.
    """
    xyz = depth2xyzmap(depth, K)  # (H, W, 3)
    valid = (mask > 0) & (depth > 0.01)
    pts = xyz[valid]  # (N, 3)
    if len(pts) < 10:
        return 0.0
    pts_centered = pts - pts.mean(axis=0)
    _, s, _ = np.linalg.svd(pts_centered, full_matrices=False)
    if s[0] < 1e-8:
        return 0.0
    return float(s[2] / s[0])  # min / max singular value


def main(args):
    # pipeline_preprocess folder is generated by robust_hoi_pipeline/pipeline_data_preprocess.py
    rgb_dir = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/rgb")
    depth_dir = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/depth_filtered")
    meta_dir = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/meta")
    mask_obj_dir = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/mask_obj")
    frame_list_file = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/frame_list.txt")

    # Load frame index list
    with open(frame_list_file, "r") as f:
        frame_indices = [int(line.strip()) for line in f if line.strip()]
    print(f"Loaded {len(frame_indices)} frames from {frame_list_file}")

    mask_pixel_counts = {}
    geometry_qualities = {}

    for frame_idx in frame_indices:
        fid = f"{frame_idx:04d}"

        mask_path = mask_obj_dir / f"{fid}.png"
        depth_path = depth_dir / f"{fid}.png"
        meta_path = meta_dir / f"{fid}.pkl"

        # Mask pixel count
        if mask_path.exists():
            mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
            mask_pixels = int((mask > 0).sum()) if mask is not None else 0
        else:
            mask = None
            mask_pixels = 0
        mask_pixel_counts[frame_idx] = mask_pixels

        # Geometry quality via SVD
        if depth_path.exists() and meta_path.exists() and mask is not None and mask_pixels > 0:
            try:
                K = _load_intrinsics(str(meta_path))
                depth = get_depth(str(depth_path))
                quality = _geometry_quality(depth, K, mask)
            except Exception as e:
                print(f"  Frame {fid}: geometry quality failed: {e}")
                quality = 0.0
        else:
            quality = 0.0
        geometry_qualities[frame_idx] = quality

        print(f"  Frame {fid}: mask_pixels={mask_pixels}, geometry_quality={quality:.4f}")

    # Filter frames: sort by mask pixel count, keep top 150
    sorted_by_mask = sorted(mask_pixel_counts.keys(), key=lambda i: mask_pixel_counts[i], reverse=True)
    mask_filtered = set(sorted_by_mask[:150])

    # Filter frames: sort by geometry quality, keep top 100
    sorted_by_geom = sorted(geometry_qualities.keys(), key=lambda i: geometry_qualities[i], reverse=True)
    geom_filtered = set(sorted_by_geom[:100])

    # Keep only frames that pass both filters, preserving original order
    filtered = [i for i in frame_indices if i in mask_filtered and i in geom_filtered]


    # Write filtered frame list
    out_path = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/frame_list_filtered.txt")
    with open(out_path, "w") as f:
        for idx in filtered:
            f.write(f"{idx}\n")
    print(f"Saved filtered frame list to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Filter frames by mask size and geometry quality for SAM3D")
    parser.add_argument("--dataset_dir", type=str, required=True)
    parser.add_argument("--scene_name", type=str, required=True)

    args = parser.parse_args()
    main(args)
