import argparse
import os
import pickle
import sys
from pathlib import Path

import cv2
import numpy as np
import torch

project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))
sys.path.insert(0, str(project_root / "../" / "third_party" / "utils_simba"))
sys.path.insert(0, str(project_root / "../" / "dependency" / "LightGlue"))

from utils_simba.depth import depth2xyzmap, get_depth, load_filtered_depth
from lightglue import SuperPoint

sys.path.insert(0, str(project_root / ".."))
from robust_hoi_pipeline.pipeline_data_preprocess import prepare_image_list


def _load_intrinsics(meta_path: str) -> np.ndarray:
    """Load camera intrinsics from meta pickle file."""
    with open(meta_path, "rb") as f:
        meta = pickle.load(f)
    return np.array(meta["camMat"], dtype=np.float32)


def _geometry_quality(depth: np.ndarray, K: np.ndarray, mask: np.ndarray) -> float:
    """Compute geometry quality via SVD of masked object point cloud.

    Returns the ratio of the smallest to largest singular value (0–1).
    A value close to 1 means the points are well-spread in 3D (good geometry);
    a value close to 0 means degenerate/planar/sparse.
    """
    xyz = depth2xyzmap(depth, K)  # (H, W, 3)
    valid = (mask > 0) & (depth > 0.01)
    pts = xyz[valid]  # (N, 3)
    if len(pts) < 10:
        return 0.0, np.zeros(3)
    pts_centered = pts - pts.mean(axis=0)
    _, s, _ = np.linalg.svd(pts_centered, full_matrices=False)
    if s[0] < 1e-8:
        return 0.0, s
    return float(s[2] / s[0]), s  # min / max singular value, singular values


def _count_feature_points(image: np.ndarray, mask: np.ndarray, extractor) -> int:
    """Count SuperPoint feature points within the object mask.

    Args:
        image: (H, W, 3) uint8 RGB image
        mask: (H, W) uint8 mask (>0 = object)
        extractor: SuperPoint model on device

    Returns:
        Number of keypoints inside the mask.
    """
    device = next(extractor.parameters()).device
    img_tensor = torch.from_numpy(image).permute(2, 0, 1).float() / 255.0
    img_tensor = img_tensor.unsqueeze(0).to(device)
    with torch.no_grad():
        feats = extractor.extract(img_tensor)
    kpts = feats["keypoints"][0].cpu().numpy()  # (N, 2) x,y
    # Count keypoints inside mask
    kpts_int = kpts.astype(int)
    h, w = mask.shape
    in_bounds = (kpts_int[:, 0] >= 0) & (kpts_int[:, 0] < w) & (kpts_int[:, 1] >= 0) & (kpts_int[:, 1] < h)
    kpts_valid = kpts_int[in_bounds]
    in_mask = mask[kpts_valid[:, 1], kpts_valid[:, 0]] > 0
    return int(in_mask.sum())


def main(args):
    # pipeline_preprocess folder is generated by robust_hoi_pipeline/pipeline_data_preprocess.py
    rgb_dir = Path(f"{args.dataset_dir}/{args.scene_name}/rgb")
    depth_dir = Path(f"{args.dataset_dir}/{args.scene_name}/depth")
    meta_dir = Path(f"{args.dataset_dir}/{args.scene_name}/meta")
    mask_obj_dir = Path(f"{args.dataset_dir}/{args.scene_name}/mask_object")
    out_dir = Path(f"{args.dataset_dir}/{args.scene_name}/SAM3D")

    # Load frame index list
    frame_indices = prepare_image_list(
        image_dir=rgb_dir,
        start=args.frame_start,
        end=args.frame_end,
        interval=args.frame_interval,
        cond_index=args.cond_idx,
    )
    print(f"Loaded {len(frame_indices)} frames from {rgb_dir}")

    mask_pixel_counts = {}

    for frame_idx in frame_indices:
        fid = f"{frame_idx:04d}"
        mask_path = mask_obj_dir / f"{fid}.png"
        if not mask_path.exists():
            raise FileNotFoundError(f"Object mask not found: {mask_path}")
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        mask_pixels = int((mask > 0).sum()) if mask is not None else 0
        mask_pixel_counts[frame_idx] = mask_pixels
        print(f"  Frame {fid}: mask_pixels={mask_pixels}")


    # Filter frames: sort by mask pixel count, keep top 150
    sorted_by_mask = sorted(mask_pixel_counts.keys(), key=lambda i: mask_pixel_counts[i], reverse=True)
    mask_filtered = set(sorted_by_mask[:args.max_mask_filtered_frames])

    mask_filtered_ordered = sorted_by_mask[:args.max_mask_filtered_frames]
    mask_out_path = out_dir / "frame_list_after_mask_filtered.txt"
    with open(mask_out_path, "w") as f:
        for idx in mask_filtered_ordered:
            f.write(f"{idx}\n")
    print(f"Saved mask-filtered frame list to {mask_out_path}")

    # Compute geometry quality only on mask-filtered frames
    geometry_qualities = {}
    for frame_idx in mask_filtered_ordered:
        fid = f"{frame_idx:04d}"
        depth_path = depth_dir / f"{fid}.png"
        meta_path = meta_dir / f"0000.pkl"
        mask_path = mask_obj_dir / f"{fid}.png"
        if not depth_path.exists():
            raise FileNotFoundError(f"Depth image not found: {depth_path}")
        if not meta_path.exists():
            raise FileNotFoundError(f"Meta file not found: {meta_path}")
        if not mask_path.exists():
            raise FileNotFoundError(f"Object mask not found: {mask_path}")
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        K = _load_intrinsics(str(meta_path))
        depth = load_filtered_depth(str(depth_path))
        quality, svs = _geometry_quality(depth, K, mask)
        geometry_qualities[frame_idx] = quality
        print(f"  Frame {fid}: geometry_quality={quality:.4f}, singular_values=({svs[0]:.4f}, {svs[1]:.4f}, {svs[2]:.4f})")

    # Filter frames: sort by geometry quality, keep top 100
    sorted_by_geom = sorted(geometry_qualities.keys(), key=lambda i: geometry_qualities[i], reverse=True)

    depth_filtered_ordered = sorted_by_geom[:args.max_geometry_filtered_frames]
    depth_out_path = out_dir / "frame_list_after_depth_filtered.txt"
    with open(depth_out_path, "w") as f:
        for idx in depth_filtered_ordered:
            f.write(f"{idx}\n")
    print(f"Saved depth-filtered frame list to {depth_out_path}")

    # Filter by feature point count (SuperPoint keypoints in object mask)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    extractor = SuperPoint(max_num_keypoints=2048).eval().to(device)

    ftp_counts = {}
    for frame_idx in depth_filtered_ordered:
        fid = f"{frame_idx:04d}"
        rgb_path = rgb_dir / f"{fid}.jpg"
        mask_path = mask_obj_dir / f"{fid}.png"


        if not rgb_path.exists():
            raise FileNotFoundError(f"RGB image not found: {rgb_path}")
        if not mask_path.exists():
            raise FileNotFoundError(f"Object mask not found: {mask_path}")
        image = cv2.imread(str(rgb_path))
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        count = _count_feature_points(image, mask, extractor)
        ftp_counts[frame_idx] = count
        print(f"  Frame {fid}: feature_points={count}")

    sorted_by_ftp = sorted(ftp_counts.keys(), key=lambda i: ftp_counts[i], reverse=True)
    ftp_filtered_ordered = sorted_by_ftp[:args.max_ftp_filter_frames]
    ftp_out_path = out_dir / "frame_list_after_ftp_filtered.txt"
    with open(ftp_out_path, "w") as f:
        for idx in ftp_filtered_ordered:
            f.write(f"{idx}\n")
    print(f"Saved feature-point-filtered frame list ({len(ftp_filtered_ordered)} frames) to {ftp_out_path}")

    # Keep only frames that pass all filters, preserving feature-point order
    filtered = [i for i in ftp_filtered_ordered if i in mask_filtered]

    # Write filtered frame list
    out_path = out_dir / "frame_list_filtered.txt"
    with open(out_path, "w") as f:
        for idx in filtered:
            f.write(f"{idx}\n")
    print(f"Saved final filtered frame list ({len(filtered)} frames) to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Filter frames by mask size and geometry quality for SAM3D")
    parser.add_argument("--dataset_dir", type=str, required=True)
    parser.add_argument("--scene_name", type=str, required=True)
    parser.add_argument("--frame_start", type=int, default=0, help="Start frame index")
    parser.add_argument("--frame_end", type=int, default=-1, help="End frame index (-1 for all)")
    parser.add_argument("--frame_interval", type=int, default=5, help="Frame sampling interval")
    parser.add_argument("--cond_idx", type=int, default=0, help="Condition frame index (always included)")
    parser.add_argument("--max_mask_filtered_frames", type=int, default=100, help="Max frames to keep after mask filtering")
    parser.add_argument("--max_geometry_filtered_frames", type=int, default=50, help="Max frames to keep after geometry filtering")
    parser.add_argument("--max_ftp_filter_frames", type=int, default=30, help="Max frames to keep after feature point filtering")

    args = parser.parse_args()
    main(args)
