import argparse
import json
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))
sys.path.insert(0, str(project_root / "third_party" / "utils_simba"))

from utils_simba.logger import get_logger

logger = get_logger(__name__)


def main(args):
    scene_dir = Path(args.scene_dir)

    # Load scores.json generated by ho3d_align_SAM3D_pts
    scores_path = scene_dir / "SAM3D_aligned_pts" / "scores.json"
    if not scores_path.exists():
        logger.error(f"{scores_path} not found.")
        return
    with open(scores_path, "r") as f:
        scores = json.load(f)
    logger.info(f"Loaded {len(scores)} scores from {scores_path}")

    # Load frame_list_after_align_filter.txt generated by pipeline_sam3d_align_filter
    filtered_path = scene_dir / "SAM3D_align_filter" / "frame_list_after_align_filter.txt"
    if not filtered_path.exists():
        logger.error(f"{filtered_path} not found.")
        return
    with open(filtered_path, "r") as f:
        filtered_ids = [line.strip() for line in f if line.strip()]
    # Normalize to zero-padded 4-digit strings to match scores.json keys
    filtered_set = {f"{int(fid):04d}" for fid in filtered_ids}
    logger.info(f"Loaded {len(filtered_set)} filtered frames from {filtered_path}")

    # Find the best id from the filtered frame list with the best (lowest) score
    best_id = None
    best_score = float("inf")
    for fid, score in scores.items():
        if fid in filtered_set and score < best_score:
            best_score = score
            best_id = fid

    if best_id is None:
        logger.error("No filtered frame found in scores.json")
        return

    logger.info(f"Best id: {best_id} (score={best_score:.4f})")

    # Save best id
    out_path = scene_dir / "SAM3D_align_filter" / "best_id.txt"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(best_id)
    logger.info(f"Saved best id to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Find best frame id from filtered frames by score")
    parser.add_argument("--scene_dir", type=str, required=True,
                        help="Scene directory containing SAM3D_aligned_pts/ and SAM3D_align_filter/")
    args = parser.parse_args()
    main(args)
