import argparse
import os
import pickle
import sys
from pathlib import Path

import cv2
import numpy as np

project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))
sys.path.insert(0, str(project_root / "../" / "third_party" / "utils_simba"))

from utils_simba.depth import depth2xyzmap, get_depth


def _load_intrinsics(meta_path: str) -> np.ndarray:
    """Load camera intrinsics from meta pickle file."""
    with open(meta_path, "rb") as f:
        meta = pickle.load(f)
    return np.array(meta["intrinsics"], dtype=np.float32)


def _geometry_quality(depth: np.ndarray, K: np.ndarray, mask: np.ndarray) -> float:
    """Compute geometry quality via SVD of masked object point cloud.

    Returns the ratio of the smallest to largest singular value (0–1).
    A value close to 1 means the points are well-spread in 3D (good geometry);
    a value close to 0 means degenerate/planar/sparse.
    """
    xyz = depth2xyzmap(depth, K)  # (H, W, 3)
    valid = (mask > 0) & (depth > 0.01)
    pts = xyz[valid]  # (N, 3)
    if len(pts) < 10:
        return 0.0, np.zeros(3)
    pts_centered = pts - pts.mean(axis=0)
    _, s, _ = np.linalg.svd(pts_centered, full_matrices=False)
    if s[0] < 1e-8:
        return 0.0, s
    return float(s[2] / s[0]), s  # min / max singular value, singular values


def main(args):
    # pipeline_preprocess folder is generated by robust_hoi_pipeline/pipeline_data_preprocess.py
    rgb_dir = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/rgb")
    depth_dir = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/depth_filtered")
    meta_dir = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/meta")
    mask_obj_dir = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/mask_obj")
    frame_list_file = Path(f"{args.dataset_dir}/{args.scene_name}/pipeline_preprocess/frame_list.txt")
    out_dir = Path(f"{args.dataset_dir}/{args.scene_name}/SAM3D")

    # Load frame index list
    with open(frame_list_file, "r") as f:
        frame_indices = [int(line.strip()) for line in f if line.strip()]
    print(f"Loaded {len(frame_indices)} frames from {frame_list_file}")

    mask_pixel_counts = {}

    for frame_idx in frame_indices:
        fid = f"{frame_idx:04d}"
        mask_path = mask_obj_dir / f"{fid}.png"
        if mask_path.exists():
            mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
            mask_pixels = int((mask > 0).sum()) if mask is not None else 0
        else:
            mask_pixels = 0
        mask_pixel_counts[frame_idx] = mask_pixels
        print(f"  Frame {fid}: mask_pixels={mask_pixels}")


    # Filter frames: sort by mask pixel count, keep top 150
    sorted_by_mask = sorted(mask_pixel_counts.keys(), key=lambda i: mask_pixel_counts[i], reverse=True)
    mask_filtered = set(sorted_by_mask[:args.max_mask_filtered_frames])

    mask_filtered_ordered = sorted_by_mask[:args.max_mask_filtered_frames]
    mask_out_path = out_dir / "frame_list_after_mask_filtered.txt"
    with open(mask_out_path, "w") as f:
        for idx in mask_filtered_ordered:
            f.write(f"{idx}\n")
    print(f"Saved mask-filtered frame list to {mask_out_path}")

    # Compute geometry quality only on mask-filtered frames
    geometry_qualities = {}
    for frame_idx in mask_filtered_ordered:
        fid = f"{frame_idx:04d}"
        depth_path = depth_dir / f"{fid}.png"
        meta_path = meta_dir / f"{fid}.pkl"
        mask_path = mask_obj_dir / f"{fid}.png"
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE) if mask_path.exists() else None
        if depth_path.exists() and meta_path.exists() and mask is not None:
            try:
                K = _load_intrinsics(str(meta_path))
                depth = get_depth(str(depth_path))
                quality, svs = _geometry_quality(depth, K, mask)
            except Exception as e:
                print(f"  Frame {fid}: geometry quality failed: {e}")
                quality, svs = 0.0, np.zeros(3)
        else:
            quality, svs = 0.0, np.zeros(3)
        geometry_qualities[frame_idx] = quality
        print(f"  Frame {fid}: geometry_quality={quality:.4f}, singular_values=({svs[0]:.4f}, {svs[1]:.4f}, {svs[2]:.4f})")

    # Filter frames: sort by geometry quality, keep top 100
    sorted_by_geom = sorted(geometry_qualities.keys(), key=lambda i: geometry_qualities[i], reverse=True)
    geom_filtered = set(sorted_by_geom[:args.max_geometry_filtered_frames])

    depth_filtered_ordered = sorted_by_geom[:args.max_geometry_filtered_frames]
    depth_out_path = out_dir / "frame_list_after_depth_filtered.txt"
    with open(depth_out_path, "w") as f:
        for idx in depth_filtered_ordered:
            f.write(f"{idx}\n")
    print(f"Saved depth-filtered frame list to {depth_out_path}")

    # Keep only frames that pass both filters, preserving original order
    filtered = [i for i in depth_filtered_ordered if i in mask_filtered]


    # Write filtered frame list
    out_path = out_dir / "frame_list_filtered.txt"
    with open(out_path, "w") as f:
        for idx in filtered:
            f.write(f"{idx}\n")
    print(f"Saved final filtered frame list to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Filter frames by mask size and geometry quality for SAM3D")
    parser.add_argument("--dataset_dir", type=str, required=True)
    parser.add_argument("--scene_name", type=str, required=True)
    parser.add_argument("--max_mask_filtered_frames", type=int, default=100, help="Max frames to keep after mask filtering")
    parser.add_argument("--max_geometry_filtered_frames", type=int, default=50, help="Max frames to keep after geometry filtering")

    args = parser.parse_args()
    main(args)
